# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Weekly build to make sure dependencies are OK
    - cron:  '30 16 * * 3'

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      # Checkout, fetch-depth=0 fetches the full repos (required for automatic versioning to work)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python3 -m build

      - name: Install package
        run: |
          pip install dist/*.tar.gz

      - run: docker pull bitcraze/builder

      - name: CI checks
        run: docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build
